# Generated by Django 5.2.3 on 2025-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
